### ISSUE TITLE
Removal of original AE2 recipes in 1.20.1

### ISSUE THREAD

**Issue by ThePhoenixIO** [RuochenFu21/CreateAppliedKinetics#6]
The recipe for the inscriber is gone, along with the recipes for the different processors with the inscriber. While it might be intended behavior this should be left to a config option as in the pack I am building I would like to leave the option for the original recipes to remain along with the create option (along with the other blocks/uitils added to the mod).

**Comment by furuochen-dev** [comment]
This will be added after I merge #4 & #5, though a current solution will be using the /datapack command to remove the datapack I used to remove the ae recipe

**Comment by zdeleter** [comment]
What is the name of the datapack?

**Comment by pernicius** [comment]
How can i disable the datapack permanently? After a restart of the server it is always enabled again.

**Comment by Obtuse-Rubber-Goose** [comment]
Half a year later, this issue is still there.. If repairing it is as simple as removing a file or merging versions, as indicated, please do it... I'd very much like to be able to use the two mods in conjunction with one another, and this mod allows it, but also breaks primary/core features of one, making it unusable..

**Comment by furuochen-dev** [comment]
Now fixed in v1.4. Pull requests are merged

**Comment by Barerock** [comment]
This is not fixed. None but the pressed silicon are enabled. Version 1.4.0-1.20.1 Forge 47.2.20
https://github.com/AppliedEnergistics/Applied-Energistics-2/issues/8196
